FROM python:3.10-slim

WORKDIR /app

COPY requirements_prod.txt /app/requirements_prod.txt

RUN pip install --no-cache-dir -r /app/requirements_prod.txt

COPY app/ /app

EXPOSE 8000

CMD ["uvicorn", "main_prod:app", "--host", "0.0.0.0", "--port", "8000"]